name: Development pipeline

on:
  push:
    branches:
      - "*"
      - "!feature/"
    tags-ignore:
      - '**'

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Workaround checkout issues
        run: |
          git fetch --tags --force
      - name: Create Package
        uses: BigWigsMods/packager@v2
        with:
          args: -n "{package-name}-$GITHUB_REF_NAME-{project-version}" -r "$(pwd)/artifact"
      - name: Get package name
        run: |
          echo "PACKAGE=$(find artifact -type f -name *.zip -printf "%f\n")" >> $GITHUB_ENV
      - name: Upload Packages
        uses: actions/upload-artifact@v3.2.0-node20
        with:
          name: Artifact
          path: /home/runner/work/ElvUI/ElvUI/artifact/
